### ISSUE TITLE
provider tidak te-register

### ISSUE THREAD

**Issue by proximacentauri99** [dptsi/laravel-modular#4]
provider yang ada di dalam modules yang baru saja dibuat tidak terpanggil.

**Comment by proximacentauri99** [comment]
@ersadishla

**Comment by durianpeople** [comment]
## Cara replicate:

1. Buat project Laravel baru (`composer create-project laravel/laravel project`)
2. Install dptsi/laravel-modular (`composer require dptsi/laravel-modular`)
3. Buat modul baru (`php artisan module:make Blog`)
4. Pasang breakpoint di method `register()` dan `boot()` setiap service provider (di `app/Modules/Blog/Providers`), lakukan debug dengan XDebug

## Expected:

Semua breakpoint dapat tercapai

## Result

Hanya breakpoint dalam method `register()` yang dapat tercapai.
